[package]
name = "timeit"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.29"
chrono = "0.4"
chrono-tz = "0.6"
colored = "2.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }